### ISSUE TITLE
Issue on page /debugging_and_troubleshooting/update/index.html

### ISSUE THREAD

**Issue by Jhonatand26** [duckietown/book-opmanual-duckiebot#81]
When I use the command for updating my duckiebot DB18 
$ dts duckiebot update ![DUCKIEBOT_NAME]

i get the next issue in the terminal: Image 'docker.io/duckietown/portainer:daffy-arm32v7' not found on registry 'docker.io'. Aborting.
![Screenshot from 2024-10-24 18-37-30](https://github.com/user-attachments/assets/c9e90cdd-0b3e-4828-898e-e636ccf290bd)

The duckiebot is ready to update in the terminal where im running "dts fleet discover"

**Comment by Tuxliri** [comment]
Hi @Jhonatand26, we have dropped support for the DB18 model, hence you might find that there will be issues popping up in the future, such as this one. To give you a hint on how you could possibly solve this, the image that the shell is trying to be pulled is [here](https://hub.docker.com/r/duckietown/portainer/tags), however we do not build it for the `arm32v7` architecture of the DB18, you could try to build it yourself from the source code in the respective repository.
